/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A content connector.
 */
@ApiModel(description = "A content connector.")
public class ConnectorSchema {
  @JsonProperty("connectorId")
  private String connectorId = null;

  @JsonProperty("contentConnectorType")
  private String contentConnectorType = null;

  @JsonProperty("configuration")
  private Object _configuration = null;

  @JsonProperty("additionalInstanceInformation")
  private Object additionalInstanceInformation = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  public ConnectorSchema connectorId(String connectorId) {
    this.connectorId = connectorId;
    return this;
  }

  /**
   * Get connectorId
   * @return connectorId
  **/
  @ApiModelProperty(value = "")
  public String getConnectorId() {
    return connectorId;
  }

  public void setConnectorId(String connectorId) {
    this.connectorId = connectorId;
  }

  public ConnectorSchema contentConnectorType(String contentConnectorType) {
    this.contentConnectorType = contentConnectorType;
    return this;
  }

  /**
   * type of this content connector
   * @return contentConnectorType
  **/
  @ApiModelProperty(value = "type of this content connector")
  public String getContentConnectorType() {
    return contentConnectorType;
  }

  public void setContentConnectorType(String contentConnectorType) {
    this.contentConnectorType = contentConnectorType;
  }

  public ConnectorSchema _configuration(Object _configuration) {
    this._configuration = _configuration;
    return this;
  }

  /**
   * configuration for this content connector, format is implementation specific
   * @return _configuration
  **/
  @ApiModelProperty(value = "configuration for this content connector, format is implementation specific")
  public Object getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(Object _configuration) {
    this._configuration = _configuration;
  }

  public ConnectorSchema additionalInstanceInformation(Object additionalInstanceInformation) {
    this.additionalInstanceInformation = additionalInstanceInformation;
    return this;
  }

  /**
   * additional information about this content connector, format is implementation specific and will only be present if the connector is enabled
   * @return additionalInstanceInformation
  **/
  @ApiModelProperty(value = "additional information about this content connector, format is implementation specific and will only be present if the connector is enabled")
  public Object getAdditionalInstanceInformation() {
    return additionalInstanceInformation;
  }

  public void setAdditionalInstanceInformation(Object additionalInstanceInformation) {
    this.additionalInstanceInformation = additionalInstanceInformation;
  }

  public ConnectorSchema enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * is this connector enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "is this connector enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorSchema connectorSchema = (ConnectorSchema) o;
    return Objects.equals(this.connectorId, connectorSchema.connectorId) &&
        Objects.equals(this.contentConnectorType, connectorSchema.contentConnectorType) &&
        Objects.equals(this._configuration, connectorSchema._configuration) &&
        Objects.equals(this.additionalInstanceInformation, connectorSchema.additionalInstanceInformation) &&
        Objects.equals(this.enabled, connectorSchema.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectorId, contentConnectorType, _configuration, additionalInstanceInformation, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorSchema {\n");
    
    sb.append("    connectorId: ").append(toIndentedString(connectorId)).append("\n");
    sb.append("    contentConnectorType: ").append(toIndentedString(contentConnectorType)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    additionalInstanceInformation: ").append(toIndentedString(additionalInstanceInformation)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

