/**
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.rusticisoftware.cloud.v2.client.model.CourseSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * CourseListSchema
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T14:21:57.917-05:00")
public class CourseListSchema   {
  @JsonProperty("courses")
  private List<CourseSchema> courses = new ArrayList<CourseSchema>();

  @JsonProperty("more")
  private String more = null;

  public CourseListSchema courses(List<CourseSchema> courses) {
    this.courses = courses;
    return this;
  }

  public CourseListSchema addCoursesItem(CourseSchema coursesItem) {
    this.courses.add(coursesItem);
    return this;
  }

   /**
   * Get courses
   * @return courses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CourseSchema> getCourses() {
    return courses;
  }

  public void setCourses(List<CourseSchema> courses) {
    this.courses = courses;
  }

  public CourseListSchema more(String more) {
    this.more = more;
    return this;
  }

   /**
   * Get more
   * @return more
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMore() {
    return more;
  }

  public void setMore(String more) {
    this.more = more;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CourseListSchema courseListSchema = (CourseListSchema) o;
    return Objects.equals(this.courses, courseListSchema.courses) &&
        Objects.equals(this.more, courseListSchema.more);
  }

  @Override
  public int hashCode() {
    return Objects.hash(courses, more);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CourseListSchema {\n");
    
    sb.append("    courses: ").append(toIndentedString(courses)).append("\n");
    sb.append("    more: ").append(toIndentedString(more)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

