/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.rusticisoftware.cloud.v2.client.model.CreateDispatchIdSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CreateDispatchListSchema
 */
public class CreateDispatchListSchema {
  @JsonProperty("dispatches")
  private List<CreateDispatchIdSchema> dispatches = null;

  public CreateDispatchListSchema dispatches(List<CreateDispatchIdSchema> dispatches) {
    this.dispatches = dispatches;
    return this;
  }

  public CreateDispatchListSchema addDispatchesItem(CreateDispatchIdSchema dispatchesItem) {
    if (this.dispatches == null) {
      this.dispatches = new ArrayList<>();
    }
    this.dispatches.add(dispatchesItem);
    return this;
  }

  /**
   * Get dispatches
   * @return dispatches
  **/
  @ApiModelProperty(value = "")
  public List<CreateDispatchIdSchema> getDispatches() {
    return dispatches;
  }

  public void setDispatches(List<CreateDispatchIdSchema> dispatches) {
    this.dispatches = dispatches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDispatchListSchema createDispatchListSchema = (CreateDispatchListSchema) o;
    return Objects.equals(this.dispatches, createDispatchListSchema.dispatches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dispatches);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDispatchListSchema {\n");
    
    sb.append("    dispatches: ").append(toIndentedString(dispatches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

