/**
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.rusticisoftware.cloud.v2.client.model.TagPostSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * RegistrationTagsBatchSchema
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-25T23:53:11.088-05:00")
public class RegistrationTagsBatchSchema   {
  @JsonProperty("registrationIds")
  private List<String> registrationIds = new ArrayList<String>();

  @JsonProperty("tags")
  private TagPostSchema tags = null;

  public RegistrationTagsBatchSchema registrationIds(List<String> registrationIds) {
    this.registrationIds = registrationIds;
    return this;
  }

  public RegistrationTagsBatchSchema addRegistrationIdsItem(String registrationIdsItem) {
    this.registrationIds.add(registrationIdsItem);
    return this;
  }

   /**
   * Get registrationIds
   * @return registrationIds
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<String> getRegistrationIds() {
    return registrationIds;
  }

  public void setRegistrationIds(List<String> registrationIds) {
    this.registrationIds = registrationIds;
  }

  public RegistrationTagsBatchSchema tags(TagPostSchema tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TagPostSchema getTags() {
    return tags;
  }

  public void setTags(TagPostSchema tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistrationTagsBatchSchema registrationTagsBatchSchema = (RegistrationTagsBatchSchema) o;
    return Objects.equals(this.registrationIds, registrationTagsBatchSchema.registrationIds) &&
        Objects.equals(this.tags, registrationTagsBatchSchema.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registrationIds, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistrationTagsBatchSchema {\n");
    
    sb.append("    registrationIds: ").append(toIndentedString(registrationIds)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

