/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * RuntimeInteractionSchema
 */
public class RuntimeInteractionSchema {
  @JsonProperty("id")
  private String id = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TRUEFALSE("TrueFalse"),
    
    CHOICE("Choice"),
    
    FILLIN("FillIn"),
    
    LONGFILLIN("LongFillIn"),
    
    LIKERT("Likert"),
    
    MATCHING("Matching"),
    
    PERFORMANCE("Performance"),
    
    SEQUENCING("Sequencing"),
    
    NUMERIC("Numeric"),
    
    OTHER("Other");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("objectives")
  private List<String> objectives = null;

  @JsonProperty("timestamp")
  private String timestamp = null;

  @JsonProperty("timestampUtc")
  private String timestampUtc = null;

  @JsonProperty("correctResponses")
  private List<String> correctResponses = null;

  @JsonProperty("weighting")
  private String weighting = null;

  @JsonProperty("learnerResponse")
  private String learnerResponse = null;

  @JsonProperty("result")
  private String result = null;

  @JsonProperty("latency")
  private String latency = null;

  @JsonProperty("description")
  private String description = null;

  public RuntimeInteractionSchema id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RuntimeInteractionSchema type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public RuntimeInteractionSchema objectives(List<String> objectives) {
    this.objectives = objectives;
    return this;
  }

  public RuntimeInteractionSchema addObjectivesItem(String objectivesItem) {
    if (this.objectives == null) {
      this.objectives = new ArrayList<>();
    }
    this.objectives.add(objectivesItem);
    return this;
  }

  /**
   * Get objectives
   * @return objectives
  **/
  @ApiModelProperty(value = "")
  public List<String> getObjectives() {
    return objectives;
  }

  public void setObjectives(List<String> objectives) {
    this.objectives = objectives;
  }

  public RuntimeInteractionSchema timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public RuntimeInteractionSchema timestampUtc(String timestampUtc) {
    this.timestampUtc = timestampUtc;
    return this;
  }

  /**
   * Get timestampUtc
   * @return timestampUtc
  **/
  @ApiModelProperty(value = "")
  public String getTimestampUtc() {
    return timestampUtc;
  }

  public void setTimestampUtc(String timestampUtc) {
    this.timestampUtc = timestampUtc;
  }

  public RuntimeInteractionSchema correctResponses(List<String> correctResponses) {
    this.correctResponses = correctResponses;
    return this;
  }

  public RuntimeInteractionSchema addCorrectResponsesItem(String correctResponsesItem) {
    if (this.correctResponses == null) {
      this.correctResponses = new ArrayList<>();
    }
    this.correctResponses.add(correctResponsesItem);
    return this;
  }

  /**
   * Get correctResponses
   * @return correctResponses
  **/
  @ApiModelProperty(value = "")
  public List<String> getCorrectResponses() {
    return correctResponses;
  }

  public void setCorrectResponses(List<String> correctResponses) {
    this.correctResponses = correctResponses;
  }

  public RuntimeInteractionSchema weighting(String weighting) {
    this.weighting = weighting;
    return this;
  }

  /**
   * Get weighting
   * @return weighting
  **/
  @ApiModelProperty(value = "")
  public String getWeighting() {
    return weighting;
  }

  public void setWeighting(String weighting) {
    this.weighting = weighting;
  }

  public RuntimeInteractionSchema learnerResponse(String learnerResponse) {
    this.learnerResponse = learnerResponse;
    return this;
  }

  /**
   * Get learnerResponse
   * @return learnerResponse
  **/
  @ApiModelProperty(value = "")
  public String getLearnerResponse() {
    return learnerResponse;
  }

  public void setLearnerResponse(String learnerResponse) {
    this.learnerResponse = learnerResponse;
  }

  public RuntimeInteractionSchema result(String result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public RuntimeInteractionSchema latency(String latency) {
    this.latency = latency;
    return this;
  }

  /**
   * Get latency
   * @return latency
  **/
  @ApiModelProperty(value = "")
  public String getLatency() {
    return latency;
  }

  public void setLatency(String latency) {
    this.latency = latency;
  }

  public RuntimeInteractionSchema description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuntimeInteractionSchema runtimeInteractionSchema = (RuntimeInteractionSchema) o;
    return Objects.equals(this.id, runtimeInteractionSchema.id) &&
        Objects.equals(this.type, runtimeInteractionSchema.type) &&
        Objects.equals(this.objectives, runtimeInteractionSchema.objectives) &&
        Objects.equals(this.timestamp, runtimeInteractionSchema.timestamp) &&
        Objects.equals(this.timestampUtc, runtimeInteractionSchema.timestampUtc) &&
        Objects.equals(this.correctResponses, runtimeInteractionSchema.correctResponses) &&
        Objects.equals(this.weighting, runtimeInteractionSchema.weighting) &&
        Objects.equals(this.learnerResponse, runtimeInteractionSchema.learnerResponse) &&
        Objects.equals(this.result, runtimeInteractionSchema.result) &&
        Objects.equals(this.latency, runtimeInteractionSchema.latency) &&
        Objects.equals(this.description, runtimeInteractionSchema.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, objectives, timestamp, timestampUtc, correctResponses, weighting, learnerResponse, result, latency, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuntimeInteractionSchema {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    objectives: ").append(toIndentedString(objectives)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    timestampUtc: ").append(toIndentedString(timestampUtc)).append("\n");
    sb.append("    correctResponses: ").append(toIndentedString(correctResponses)).append("\n");
    sb.append("    weighting: ").append(toIndentedString(weighting)).append("\n");
    sb.append("    learnerResponse: ").append(toIndentedString(learnerResponse)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

