/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.rusticisoftware.cloud.v2.client.model.PaginatedList;
import com.rusticisoftware.cloud.v2.client.model.UserInvitationSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * UserInvitationList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-22T15:00:21.693-05:00")
public class UserInvitationList extends PaginatedList {
  @JsonProperty("userInvitations")
  private List<UserInvitationSchema> userInvitations = null;

  public UserInvitationList userInvitations(List<UserInvitationSchema> userInvitations) {
    this.userInvitations = userInvitations;
    return this;
  }

  public UserInvitationList addUserInvitationsItem(UserInvitationSchema userInvitationsItem) {
    if (this.userInvitations == null) {
      this.userInvitations = new ArrayList<>();
    }
    this.userInvitations.add(userInvitationsItem);
    return this;
  }

  /**
   * A list of user invitation objects.
   * @return userInvitations
  **/
  @ApiModelProperty(value = "A list of user invitation objects.")
  public List<UserInvitationSchema> getUserInvitations() {
    return userInvitations;
  }

  public void setUserInvitations(List<UserInvitationSchema> userInvitations) {
    this.userInvitations = userInvitations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInvitationList userInvitationList = (UserInvitationList) o;
    return Objects.equals(this.userInvitations, userInvitationList.userInvitations) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userInvitations, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInvitationList {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    userInvitations: ").append(toIndentedString(userInvitations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

