/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.rusticisoftware.cloud.v2.client.model.XapiActivity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#4162-contextactivities-property
 */
@ApiModel(description = "https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#4162-contextactivities-property")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-19T22:54:47.497-06:00")
public class XapiContextActivity {
  @JsonProperty("parent")
  private List<XapiActivity> parent = new ArrayList<XapiActivity>();

  @JsonProperty("grouping")
  private List<XapiActivity> grouping = new ArrayList<XapiActivity>();

  @JsonProperty("category")
  private List<XapiActivity> category = new ArrayList<XapiActivity>();

  @JsonProperty("other")
  private List<XapiActivity> other = new ArrayList<XapiActivity>();

  public XapiContextActivity parent(List<XapiActivity> parent) {
    this.parent = parent;
    return this;
  }

  public XapiContextActivity addParentItem(XapiActivity parentItem) {
    this.parent.add(parentItem);
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<XapiActivity> getParent() {
    return parent;
  }

  public void setParent(List<XapiActivity> parent) {
    this.parent = parent;
  }

  public XapiContextActivity grouping(List<XapiActivity> grouping) {
    this.grouping = grouping;
    return this;
  }

  public XapiContextActivity addGroupingItem(XapiActivity groupingItem) {
    this.grouping.add(groupingItem);
    return this;
  }

   /**
   * Get grouping
   * @return grouping
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<XapiActivity> getGrouping() {
    return grouping;
  }

  public void setGrouping(List<XapiActivity> grouping) {
    this.grouping = grouping;
  }

  public XapiContextActivity category(List<XapiActivity> category) {
    this.category = category;
    return this;
  }

  public XapiContextActivity addCategoryItem(XapiActivity categoryItem) {
    this.category.add(categoryItem);
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<XapiActivity> getCategory() {
    return category;
  }

  public void setCategory(List<XapiActivity> category) {
    this.category = category;
  }

  public XapiContextActivity other(List<XapiActivity> other) {
    this.other = other;
    return this;
  }

  public XapiContextActivity addOtherItem(XapiActivity otherItem) {
    this.other.add(otherItem);
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<XapiActivity> getOther() {
    return other;
  }

  public void setOther(List<XapiActivity> other) {
    this.other = other;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XapiContextActivity xapiContextActivity = (XapiContextActivity) o;
    return Objects.equals(this.parent, xapiContextActivity.parent) &&
        Objects.equals(this.grouping, xapiContextActivity.grouping) &&
        Objects.equals(this.category, xapiContextActivity.category) &&
        Objects.equals(this.other, xapiContextActivity.other);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parent, grouping, category, other);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XapiContextActivity {\n");
    
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    grouping: ").append(toIndentedString(grouping)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

