/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rusticisoftware.cloud.v2.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ZoomiCourseOptionsSchema
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-06T09:44:40.358-06:00")
public class ZoomiCourseOptionsSchema {
  @JsonProperty("nti")
  private String nti = null;

  @JsonProperty("cta")
  private String cta = null;

  public ZoomiCourseOptionsSchema nti(String nti) {
    this.nti = nti;
    return this;
  }

   /**
   * Get nti
   * @return nti
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNti() {
    return nti;
  }

  public void setNti(String nti) {
    this.nti = nti;
  }

  public ZoomiCourseOptionsSchema cta(String cta) {
    this.cta = cta;
    return this;
  }

   /**
   * Get cta
   * @return cta
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCta() {
    return cta;
  }

  public void setCta(String cta) {
    this.cta = cta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZoomiCourseOptionsSchema zoomiCourseOptionsSchema = (ZoomiCourseOptionsSchema) o;
    return Objects.equals(this.nti, zoomiCourseOptionsSchema.nti) &&
        Objects.equals(this.cta, zoomiCourseOptionsSchema.cta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nti, cta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZoomiCourseOptionsSchema {\n");
    
    sb.append("    nti: ").append(toIndentedString(nti)).append("\n");
    sb.append("    cta: ").append(toIndentedString(cta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

